- name: configure gitlab (fqdn)
  debconf:
      name: 'gitlab'
      question: 'gitlab/fqdn'
      vtype: 'string'
      value: '{{ gitlab_fqdn }}'
- name: configure gitlab (ssl)
  debconf:
      name: 'gitlab'
      question: 'gitlab/ssl'
      vtype: 'string'
      value: "false"
- name: install gitlab packages
  apt:
      name: '{{ item }}'
      state: latest
      install_recommends: false
  with_items:
      - gitlab
