# see /usr/share/doc/gitlab/README.Debian.gz
# for instruction on how to migrate and reset root password

- name: configure gitlab (fqdn)
  debconf:
      name: 'gitlab'
      question: 'gitlab/fqdn'
      vtype: 'string'
      value: '{{ fqdn }}'

- include_role:
    name: service
  vars:
    service_name: gitlab
    service_packages:
      - gitlab

- name: remove debian nginx configuration
  file:
    path: '/etc/nginx/sites-enabled/{{ fqdn }}'
    state: absent

- name: copy my-gitlab.yml
  template:
      src: "gitlab.yml.j2"
      dest: "/etc/gitlab/gitlab.yml"
  notify: restart gitlab
