---
- name: install dovecot and associated packages
  apt: name={{ item }} state=latest
  with_items:
      - dovecot-core
      - dovecot-imapd
      - dovecot-pop3d
- name: start dovecot at boot
  service: name=dovecot state=started enabled=yes
