---
- include: service.yaml
  service_name: nginx
  service_packages:
      - nginx
- name: disable nginx default configuration
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify: restart nginx
- name: upload nginx proxy configuration
  template:
      src: proxy_config.j2
      dest: "/etc/nginx/sites-available/{{ config_name }}"
  tags:
      - proxy
  notify:
      - enable nginx configuration
      - restart nginx
