---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: blogs
    - role: ssh_server
      connection: lxc_ssh
      ansible_docker_extra_args: blogs
- hosts: blogs
  roles:
      - role: wordpress
        site_names:
          - kaos
