---
- hosts: 'gandalf'
  roles:
    - role: 'openvpn'
      routes:
        - '10.151.42.0 255.255.255.0'
        - '10.151.40.0 255.255.255.0'
    - role: 'ssh_server'
      ansible_distribution: 'openwrt'

- hosts: 'status'
  roles:
    - role: 'icinga2-monitoring'
...
