---
- import_playbook: 'prepare_lxc_guest.yaml'
  vars:
    host: 'matrix'
    vm_size: '20G'
    unprivileged: true

- hosts: 'matrix'
  vars:
    nginx_proxy_protocol: true
    reverse_proxy_proxy_protocol: true
  roles:
    - role: 'dns_record'
    - role: 'reverse_proxy'
      reverse_proxy_site_fqdn:
        - 'matrix.{{ domain }}'
        - 'riot.sestograd.org'
    - role: 'matrix-synapse'
      coturn_host: 'turn'
      coturn_port: '88'
      coturn_fqdn: '{{ domain }}'
    - role: 'riot-web'
      riot_web_nginx_fqdn: "riot.sestograd.org"
    - role: 'monitoring-agent'

- hosts: 'monitoring_hosts'
  roles:
    - role: 'icinga2-monitoring'
...
