---
- import_playbook: 'prepare_lxc_guest.yaml'
  vars:
    host: 'matrix'
    vm_size: '20G'

- hosts: 'matrix'
  vars:
    nginx_proxy_protocol: true
    reverse_proxy_proxy_protocol: true
  roles:
    - role: 'dns_record'
    - role: 'reverse_proxy'
      reverse_proxy_site_fqdn:
        - 'matrix.{{ domain }}'
        - 'riot.sestograd.org'
    #- role: 'coturn'
    #- role: 'matrix-synapse'
    - role: 'riot-web'
    - role: 'monitoring-agent'

- hosts: 'monitoring_hosts'
  roles:
    - role: 'icinga2-monitoring'
...
