---
- import_playbook: 'prepare_lxc_guest.yaml'
  vars:
    host: 'ldap'
    vm_size: '1G'

- hosts: 'ldap'
  roles:
      - role: 'dns_record'
      - role: 'ldap'
        virtual_domains:
          - '{{ domain }}'
        # Default values:
        #ldap_tls_enabled: true
        #ldap_check_tree: true
      - role: 'monitoring-agent'

- hosts: 'monitoring_hosts'
  roles:
    - role: 'icinga2-monitoring'
...
