---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: ldap
    - role: ssh_server
      ansible_connection: ssh_lxc
      ansible_ssh_lxc_name: ldap
- hosts: ldap
  roles:
      - role: dns_record
      - role: ldap
        ldap_domain: 'lilik.it'
        ldap_organization: 'LILiK'
- hosts: status
  roles:
    - role: icinga2-monitoring
