---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: ldap
    - role: ssh_server
      connection: lxc_ssh
      ansible_docker_extra_args: ldap
- hosts: ldap
  roles:
      - role: ldap
        ldap_domain: 'lilik.it'
        ldap_organization: 'LILiK'
