---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: lists
    - role: ssh_server
      connection: lxc_ssh
      ansible_docker_extra_args: lists
- hosts: lists
  roles:
      - role: dns_record
      - role: sympa
