---
# - hosts: biff
#   roles:
#     - role: lxc_guest
#       vm_name: lists
#       distro: sid
#     - role: ssh_server
#       ansible_connection: lxc_ssh
#       ansible_docker_extra_args: lists
- hosts: lists
  roles:
      # - role: dns_record
      # - role: reverse_proxy
      #   hostname: lists2
      - role: mailman3
- hosts: status
  roles:
    - role: icinga2-monitoring
