---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: logger

- hosts: all
  tasks:
    - name: Install rsyslog on client
      apt:
        name: rsyslog
        update_cache: yes

    - name: Enable rsyslog daemon
      service:
        name: rsyslog
        enable: yes
        state: started
