---
- hosts: biff
  roles:
      - role: lxc_guest
        vm_name: logger
- hosts: logger
- tasks:
    - name: Install rsyslog
      apt:
        name: rsyslog
        update_cache: yes

    - name: Enable rsyslog daemon
      service:
        name: rsyslog
        enable: yes
        state: started
