---
- hosts: biff
  roles:
      - role: lxc_guest
        vm_name: login
        distro: stretch
      - role: ssh_server
        ansible_connection: ssh_lxc
        ansible_ssh_lxc_name: login
- hosts: login
  roles:
      - role: dns_record
      - role: reverse_proxy
        hostname: login
      - role: login
- hosts: status
  roles:
    - role: icinga2-monitoring
