---
- hosts: biff
  roles:
      - role: lxc_guest
        vm_name: mail
- hosts: mail
  roles:
      - role: postfix
        ldap_server: "{{ hostvars['ldap'].ansible_host }}"
        fqdn_domain: "lilik.it"
