---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: mail
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: mail
- hosts: mail
  roles:
      - role: dns_record
      - role: postfix
        ldap_server: "{{ hostvars['ldap'].ansible_host }}"
        fqdn_domain: "mail.lilik.it"
        lists_server: "{{ hostvars['lists'].ansible_host }}"
      - role: dovecot
        domain: "lilik.it"
        fqdn_domain: "mail.lilik.it"
        ldap_server: "{{ hostvars['ldap'].ansible_host }}"
- hosts: status
  roles:
    - role: icinga2-monitoring
