---
- hosts: 'matrix'
  gather_facts: false
  tags:
    - 'lxc'
  tasks:
    - import_role: name='lxc_guest'
      vars:
        vm_name: '{{ inventory_hostname }}'
        vm_size: '2G'
        vg_name: '{{ hostvars[ansible_lxc_host]["vg_name"] }}'
      delegate_to: '{{ ansible_lxc_host }}'
    - set_fact: ansible_connection='ssh_lxc'
    - setup:
    - import_role: name='ssh_server'
    - set_fact: ansible_connection='ssh'

- hosts: 'matrix'
  roles:
    - role: 'dns_record'
    - role: 'reverse_proxy'
      reverse_proxy_site_fqdns:
        - 'matrix.{{ domain }}'
        - 'riot.{{ domain }}'
    - role: 'coturn'
    - role: 'matrix-synapse'
    - role: 'riot-web'

- hosts: 'status'
  roles:
    - role: 'icinga2-monitoring'
