---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: matrix
      distro: sid
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: matrix
- hosts: matrix
  roles:
    - role: dns_record
    - role: reverse_proxy
  tasks:
    - name: Install synapse
      apt:
        name: "{{ item }}"
      with_items:
        - matrix-synapse
