---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: matrix
      distro: sid
    - role: ssh_server
      ansible_connection: ssh_lxc
      ansible_ssh_lxc_name: matrix
- hosts: matrix
  roles:
    - role: dns_record
    - role: reverse_proxy
    - role: matrix-synapse
    - role: riot-web
- hosts: status
  roles:
    - role: icinga2-monitoring
