---
- import_playbook: 'prepare_lxc_guest.yaml'
  vars:
    host: 'cloud'
    vm_size: '4G'

- hosts: 'cloud'
  roles:
    - role: 'dns_record'
    - role: 'reverse_proxy'
    - role: 'nextcloud'
    - role: 'monitoring-agent'

- hosts: 'monitoring_hosts'
  roles:
    - role: 'icinga2-monitoring'
...
