---
- hosts: vm_hosts
  tasks:
    - name: install lxc related packages
      apt: name={{ item }} state=latest
      with_items:
          - lxc
          - lxc-dev
          - python
          - python-dev
          - python-pip
    - name: install lxc python support
      pip: name=lxc-python2 state=latest
    - name: install utilities
      apt: name=vim state=latest
    - name: add ca pub key
      command: |
              echo "ssh-rsa {{ user_ca_key }}" > /etc/ssh/user_ca.pub
              echo "TrustedUserCAKeys /etc/ssh/user_ca.pub" >> /etc/ssh/sshd_config
    - name: restart ssh
      service: name=ssh state=restarted
