---
- hosts: vm_hosts
  vars:
    management_vlan: 9
    virtual_machine_vlan: 13
  tasks:
    - name: install lxc related packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      with_items:
          - lxc
          - python
          - python-lxc

    - name: install network bridge utilities
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      with_items:
        - bridge-utils
        - vlan
      notify: restart networking
    # We should fix this bug. We really should. It's a bug.
    # Bridge-utils requires a complete system reboot to enable the new bridge.
    - name: configure network bridge with vlans
      template:
          src: templates/interfaces.j2
          dest: /etc/network/interfaces
      notify: restart networking

    - name: install utilities
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 3600
      with_items:
          - vim
          - htop

  - name: enable lvm wipe signature
      lineinfile:
        dest: /etc/lvm/lvm.conf
        state: present
        line: "        wipe_signatures_when_zeroing_new_lvs = 1"
        regexp: "^\s*wipe_signatures_when_zeroing_new_lvs = 0"
      notify: restart lvm
  handlers:
      - name: restart networking
        service:
          name: networking
          state: reloaded
      - name: restart lvm
        service:
          name: lvm
          state: reloaded
      - name: restart sshd
        service:
          name: networking
          state: reloaded
