---
- hosts: vm_hosts
  roles:
    - role: ssh_server
  vars:
    management_vlan: 9
    virtual_machine_vlan: 13
  tasks:
    - name: install lxc related packages
      apt:
        pkg:
          - lxc
          - python3
          - python3-lxc
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: install common lxc filesystem support
      apt:
        name: xfsprogs
        state: present

    - name: install network bridge utilities
      apt:
        pkg:
          - bridge-utils
          - vlan
        state: present
        update_cache: yes
        cache_valid_time: 3600
      notify: restart networking
    # We should fix this bug. We really should. It's a bug.
    # Bridge-utils requires a complete system reboot to enable the new bridge.
    - name: configure network bridge with vlans
      template:
        src: templates/interfaces.j2
        dest: /etc/network/interfaces
      notify: restart networking


    - name: install utilities
      apt:
        pkg:
          - vim
          - htop
        state: present
        update_cache: yes
        cache_valid_time: 3600

    - name: enable lvm wipe signature
      lineinfile:
        dest: /etc/lvm/lvm.conf
        state: present
        line: "	wipe_signatures_when_zeroing_new_lvs = 0"
        regexp: '^\s*.+wipe_signatures_when_zeroing_new_lvs = '
      notify: restart lvm
  handlers:
    - name: restart networking
      service:
        name: networking
        state: restarted
    - name: restart lvm
      shell: /etc/init.d/lvm2 reload

- hosts: status
  roles:
    - role: icinga2-monitoring
