---
- import_playbook: 'prepare_lxc_guest.yaml'
  vars:
    host: 'projects'
    vm_size: '4G'

- hosts: 'projects'
  roles:
    - role: 'dns_record'
    - role: 'reverse_proxy'
      reverse_proxy_site_fqdn:
        - 'projects.{{ domain }}'
        - 'mattermost.{{ domain }}'
    - role: 'gitlab'
    - role: 'monitoring-agent'

- hosts: 'monitoring_hosts'
  roles:
    - role: 'icinga2-monitoring'
...
