---
- hosts: emmett
  roles:
    - role: lxc_guest
      vm_name: projects2
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: projects2
- hosts: projects2
  roles:
    - role: dns_record
    - role: reverse_proxy
      hostname: projects2
    - role: gitlab
- hosts: status
  roles:
    - role: icinga2-monitoring
