---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: projects
      # distro: sid
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: projects
- hosts: projects
  roles:
      - role: dns_record
      - role: gitlab
