---
- hosts: biff
  roles:
      - role: lxc_guest
        vm_name: pydio
        vm_size: 30G
        distro: stretch
- hosts: pydio
  tasks:
    - name: Add syncthing repo key
      apt_key:
        url: "https://syncthing.net/release-key.txt"
        state: present
    - name: Add syncthing
      apt_repository:
        repo: "deb http://apt.syncthing.net/ syncthing release"
        state: present
    - name: Install syncthing
      apt:
        name: syncthing
        state: present
        update_cache: yes
    - name: Enable syncthing
      service:
        name: syncthing
        state: started
        enabled: yes
