---
- import_playbook: 'prepare_lxc_guest.yaml'
  vars:
    host: 'status'
    vm_size: '2G'

- hosts: 'status'
  roles:
      - role: 'dns_record'
      - role: 'reverse_proxy'
      - role: 'icinga2'


- hosts: 'status'
  roles:
    - role: 'icinga2-monitoring'
...
