- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: status
      distro: stretch
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: status
- hosts: status
  roles:
      - role: dns_record
      - role: icinga2
      - role: reverse_proxy
- hosts: status
  roles:
    - role: icinga2-monitoring
