---
- hosts: lilikhost
  roles:
    - role: lxc_guest
      vm_name: team
    - role: ssh_server
      connection: lxc_ssh
      ansible_docker_extra_args: team
- hosts: team
  roles:
      - role: mattermost
      - role: nginx
        server_name: "team.lilik.it"
        config_name: "mattermost"
        remote_host: "http://127.0.0.1:8065"
