---
- hosts: lilikhost
  roles:
      - role: lxc_guest
        vm_name: team
- hosts: team
  roles:
      - role: mattermost
      - role: nginx_proxy
        server_name: "team.lilik.it"
        config_name: "mattermost"
        remote_host: "http://127.0.0.1:8065"
