---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: users
    - role: ssh_server
      connection: lxc_ssh
      ansible_docker_extra_args: users
- hosts: users
  roles:
      - role: fail2ban
      - role: pam-ldap
        ldap_server: "{{ hostvars['ldap'].ansible_host }}"
      - role: apache2
        user_dir: true
