---
- hosts: emmett
  roles:
    - role: lxc_guest
      vm_name: ca
      distro: sid
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: ca

- hosts: ca
  roles:
    - role: dns_record
    - role: reverse_proxy
    - role: nginx
      config_name: "ca"
      server_fqdn: "ca.lilik.it"
- hosts: status
  roles:
    - role: icinga2-monitoring
