---
- hosts: biff
  roles:
    - role: lxc_guest
      vm_name: webmail
    - role: ssh_server
      ansible_connection: lxc_ssh
      ansible_docker_extra_args: webmail
- hosts: webmail
  roles:
      - role: dns_record
      - role: roundcube
        mail_server: "mail.dmz.lilik"
- hosts: status
  roles:
    - role: icinga2-monitoring
