---
host_fqdn: '{{ ansible_hostname }}.dmz.{{ domain }}'
monitoring_vhosts: []
gitlab_nginx_main_fqdn: '{{ ansible_hostname }}.{{ domain }}'
gitlab_nginx_mattermost_fqdn: 'mattermost.{{ domain }}'
gitlab_ssh_port: 8022
gitlab_enable_https: true
gitlab_enable_mattermost: true
gitlab_nginx_proxy_protocol: true
ldap_tls_server_ca: '{{ tls_root_ca }}'
ldap_domain: '{{ domain }}'
ldap_server: 'ldap1.dmz.{{ domain }}'
ldap_basedn: 'dc={{ ldap_domain.replace(".", ",dc=") }}'
...
