- name: Install Https for APT
  apt: name=apt-transport-https update_cache=yes
- name: Install sqlite database
  apt: name=sqlite3
- name: Install git
  apt: name=git
- name: Add the repository key to system
  apt_key: url=https://deb.packager.io/key state=present
- name: Add the package.io repository to the list
  apt_repository: repo='deb https://deb.packager.io/gh/pkgr/gogs jessie pkgr' state=present
- name: Install Gogs
  apt: name=gogs update_cache=yes
- name: Start at boot
  service: #TODO
