### DEPRECATED -> import role `ca_cert` instead
- debug:
    msg: "Warning, deprecated"

- name: 'CA_MANAGER | sending request to ca...'
  raw: '{{ ca_request | to_json }}'
  delegate_to: 'authorities_request'
  delegate_facts: True
  register: request_result
  failed_when: '( request_result.stdout | from_json ).failed'
