- name: configure Postfix (domain)
  debconf:
      name: 'postfix'
      question: 'postfix/domainpostfix/main_mailer_type'
      vtype: 'string'
      value: 'Internet Site'
- name: configure Postfix (organization)
  debconf:
      name: 'postfix'
      question: 'postfix/mailname'
      vtype: 'string'
      value: 'lilik.it'

- include: service.yaml
  vars:
    service_name: postfix
    service_packages:
      - postfix
      - postfix-ldap
      # TODO: log, add a centralized log server
      - rsyslog

- name: upload ldap-aliases.cf
  template:
     src: ldap-aliases.cf.j2
     dest: "/etc/postfix/ldap-aliases.cf"
  notify: restart postfix

- lineinfile: dest=/etc/postfix/main.cf line="virtual_alias_maps = proxy:ldap:/etc/postfix/ldap-aliases.cf"
  notify: restart postfix

- name: upload ldap-domains.cf
  template:
     src: ldap-domains.cf.j2
     dest: "/etc/postfix/ldap-domains.cf"
  notify: restart postfix

- lineinfile: dest=/etc/postfix/main.cf line="virtual_mailbox_domains = proxy:ldap:/etc/postfix/ldap-domains.cf"
  notify: restart postfix

- name: upload ldap-accounts.cf
  template:
     src: ldap-accounts.cf.j2
     dest: "/etc/postfix/ldap-accounts.cf"
  notify: restart postfix

- lineinfile: dest=/etc/postfix/main.cf line="virtual_mailbox_maps = proxy:ldap:/etc/postfix/ldap-accounts.cf"
  notify: restart postfix

- lineinfile: dest=/etc/postfix/main.cf line="mydestination = mail.lilik.it, lists.lilik.it, localhost" regexp='mydestination =' state=present
  notify: restart postfix
