- name:
  lineinfile:
    dest: '/etc/hosts'
    line: '{{ ansible_default_ipv4.address }} {{ host_fqdn }}.'
    regexp: '^\s*\S* {{ host_fqdn }}.'
  delegate_to: gandalf
  register: hosts

- name: dnsmasq force hosts reload
  command: "killall -HUP dnsmasq"
  delegate_to: gandalf
  when: hosts.changed
