---
- name: install dokuwiki and associated packages
  apt: name={{ item }} state=latest
  with_items:
      - dokuwiki
- name: add nginx config for docukiwi
  template:
      src: docuwiki_nginx.j2
      dest: "/etc/nginx/sites-available/{{ config_name }}"
  notify:
      - enable nginx configuration
      - restart nginx
