---
- name: install dokuwiki and associated packages
  apt: name={{ item }} state=latest
  with_items:
      - php5-cgi
      - php5-fpm
      - php5-gd
      - dokuwiki
- name: copy Dokuwiki main configuration
  copy: >
    src=local.php dest=/etc/dokuwiki/local.php
