- name: add jessie-backports repository
  apt_repository: repo='deb http://ftp.debian.org/debian jessie-backports main' state=present

- name: install roundcube packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
      - roundcube-sqlite3
      - roundcube
      - roundcube-plugins
  notify:
      - restart nginx

- name: copy lilik-150x54.png
  copy:
    src: lilik-150x54.png
    dest: /usr/share/roundcube/skins/classic/images/

- name: copy my-roundcube.php
  template:
      src: "my-roundcube.php.j2"
      dest: "/etc/roundcube/my-roundcube.php"
      mode: 0640
      owner: root
      group: www-data

- name: copy test_ssl_ca.crt
  copy:
      src: "test_ssl_ca.crt"
      dest: "/usr/local/share/ca-certificates/test_ssl_ca.crt"
      mode: 0444
  notify: update-ca-certificates

- name: include my-roundcube.php
  lineinfile:
    dest: /etc/roundcube/config.inc.php
    insertafter: '\?>'
    line: include_once("/etc/roundcube/my-roundcube.php");
