---
- include_role:
    name: service
  vars:
    service_name: mysql
    service_packages:
      - mysql-server
- name: Install python bindings to mysql
  apt:
    name: python-mysqldb
    update_cache: yes
