---
- include: service.yaml
  vars:
    service_name: nginx

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False

- name: enable nginx configuration
  file:
      src: "/etc/nginx/sites-available/{{ config_name }}"
      dest: "/etc/nginx/sites-enabled/{{ config_name }}"
      state: link
  notify: restart nginx
