---
- include: service.yaml
  # static: yes # see static include issue: https://github.com/ansible/ansible/issues/13485
  vars:
    service_name: nginx
    service_packages:
      - nginx

- name: validate nginx configuration
  command: nginx -t -c /etc/nginx/nginx.conf
  changed_when: False
