---
- block:
    - import_tasks: '01-install.yaml'
      tags:
        - 'install'
        - 'role::ssh_server::install'
    - import_tasks: '02-configure.yaml'
      tags:
        - 'configure'
        - 'role::ssh_server::configure'
    #- import_tasks: '03-monitoring.yaml'
    #  tags:
    #    - 'monitoring'
  tags:
    - 'role::ssh_server'
...
