---
- name: install sympa and associated packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - sympa
    - wwsympa
    - fcgiwrap
  notify:
      - restart nginx
