- include_role:
    name: 'service'
  vars:
    service_name: 'icinga2'
  tags:
    - 'monitoring'

- debug:
    var: 'monitoring_facts'

- name: 'MONITORING | configure HOST/{{ item.key }}'
  template:
    src: 'host.conf.j2'
    dest: "/etc/icinga2/conf.d/hosts/{{ item.key }}.conf"
  loop: '{{ monitoring_facts|dict2items }}'
  notify: 'reload icinga2'
  tags:
    - 'monitoring'
