---
# connect to the hosts and treat them as reverse proxies
# create the directories for nginx configuration 
# and the required files for http/https (with sni)
# proxying
- name: Create the http.conf directory for nginx
  file:
    state: directory
    dest: "/etc/nginx/http.conf.d"

- name: Upload http to reverse proxy
  template:
    src: http.j2
    dest: "/etc/nginx/http.conf.d/http_{{ hostname }}.conf"

- name: Create the map.conf directory for nginx
  file:
    state: directory
    dest: "/etc/nginx/map.conf.d"

- name: Create the upstream.conf directory for nginx
  file:
    state: directory
    dest: "/etc/nginx/upstream.conf.d"

- name: Upload mappings to reverse proxy
  template:
    src: map.j2
    dest: "/etc/nginx/map.conf.d/map_{{ hostname }}.conf"

- name: Upload upstream to reverse proxy
  template:
    src: upstream.j2
    dest: "/etc/nginx/upstream.conf.d/upstream_{{ hostname }}.conf"
