---
- name: configure icinga2-ido-pgsql (host)
  debconf:
      name: 'icinga2-ido-pgsql'
      question: 'icinga2-ido-pgsql/remote/host'
      vtype: 'string'
      value: 'localhost'

- name: configure icinga2-ido-pgsql (enable)
  debconf:
      name: 'icinga2-ido-pgsql'
      question: 'icinga2-ido-pgsql/enable'
      vtype: 'boolean'
      value: true

- name: configure icinga2-ido-pgsql (dbconfig-install)
  debconf:
      name: 'icinga2-ido-pgsql'
      question: 'icinga2-ido-pgsql/dbconfig-install'
      vtype: 'boolean'
      value: true

- name: configure icinga2-ido-pgsql (dbconfig-reinstall)
  debconf:
      name: 'icinga2-ido-pgsql'
      question: 'icinga2-ido-pgsql/dbconfig-reinstall'
      vtype: 'boolean'
      value: true


# - name: nasty dpkg-reconfigure
#   command: "dpkg-reconfigure --frontend noninteractive icinga2-ido-pgsql"
#
# - name: configure icinga2-ido-pgsql (dbconfig-reinstall)
#   debconf:
#       name: 'icinga2-ido-pgsql'
#       question: 'icinga2-ido-pgsql/dbconfig-reinstall'
#       vtype: 'boolean'
#       value: false


- include_role:
    name: service
  vars:
    service_name: icinga2
    service_packages:
      - icinga2-ido-pgsql
      - monitoring-plugins
      - nagios-plugins-contrib
      - icinga2
      - icingacli
      - php-ldap
      - php-pgsql
      - php-intl
      - php-imagick
      - icingaweb2-module-monitoring
      - icingaweb2
      # TODO: log, add a centralized log server
      - rsyslog
      - rsync

- name: enable ido-pgsql and command features
  command: "icinga2 feature enable ido-pgsql command"
  register: icinga2_features
  changed_when: "'Enabling' in icinga2_features.stdout"
  notify: restart icinga2
- name: 'LDAP | upload client root ca'
  copy:
    content: '{{ tls_root_ca }}'
    dest: '/etc/ldap/root_ca.crt'
  tags:
    - 'tls_int'

- name: 'LDAP | configure client'
  copy:
    src: 'ldap.conf'
    dest: '/etc/ldap/ldap.conf'
  when: ldap_tls_enabled

- name: 'LDAP | generate client service password'
  gen_passwd: 'length=32'
  register: 'new_passwd'
  no_log: true
  tags:
    - 'service_password'

- name: 'LDAP | set client service password on server'
  delegate_to: 'localhost'
  ldap_passwd:
    dn: 'cn={{ ansible_hostname }},ou=Server,{{ ldap_basedn }}'
    passwd: '{{ new_passwd.passwd }}'
    server_uri: 'ldap://{{ ldap_server }}'
    start_tls: '{{ ldap_tls_enabled }}'
    bind_dn: '{{ ldap_admin_dn }}'
    bind_pw: '{{ ldap_admin_pw }}'
  no_log: true
  tags:
    - 'service_password'


- name: 'configure IcingaWeb2 (static files)'
  synchronize:
    src: 'icingaweb2'
    dest: '/etc'
    rsync_opts:
        - "--chmod=Du+rwx,Dg+rwx,Do-rwx,Fu+rw,Fg+rw,Fo-rwx"
        - "--chown=root:icingaweb2"

- name: 'create enabledModules folder'
  file:
    path: '/etc/icingaweb2/enabledModules/'
    state: 'directory'
    owner: 'root'
    group: 'icingaweb2'
    mode: '0770'

- name: 'enable IcingaWeb2 monitoring plugin'
  file:
    src: '/usr/share/icingaweb2/modules/monitoring'
    dest: '/etc/icingaweb2/enabledModules/monitoring'
    state: 'link'

- name:
  command: grep -Po 'password = "\K.*?(?=")' /etc/icinga2/features-available/ido-pgsql.conf
  register: icinga2_password
  changed_when: false

- name: 'configure IcingaWeb2 (templates)'
  template:
    src: 'icingaweb2/{{ item }}.j2'
    dest: '/etc/icingaweb2/{{ item }}'
    owner: 'root'
    group: 'icingaweb2'
    mode: '0660'
  loop:
    - 'resources.ini'
    - 'authentication.ini'
    - 'groups.ini'

- name: add nginx configurations
  template:
    src: icinga.conf
    dest: "/etc/nginx/locations/{{ server_fqdn }}/service.conf"
  notify:
    - restart nginx
