---
- block:
  - name: 'DEBIAN | install {{ service_name }}'
    apt:
      pkg: '{{ service_packages }}'
      state: 'present'
      update_cache: true
      cache_valid_time: 3600
      install_recommends: '{{ install_recommends | default("no") }}'
    tags:
      - 'packages'

  - name: 'DEBIAN | start {{ service_name }} at boot'
    service:
      name: '{{ service_name }}'
      enabled: true
  when: ansible_distribution != 'openwrt'

- block:
  - name: 'OPENWRT | install {{ service_name }}'
    opkg:
      name: '{{ service_packages | join(" ") }}'
      state: 'present'
      update_cache: true
    tags:
      - 'packages'

  - set_fact:
      service_name: 'sshd'
    when: service_name == 'ssh'

  - openwrt_init:
      name: '{{ service_name }}'
      enabled: true
  when: ansible_distribution == 'openwrt'
