- name: install postgresql
  apt: name={{ item }} state=latest
  with_items:
      - postgresql
      - postgresql-contrib
      - python-psycopg2
- name: start postgresql at boot
  service: name=postgresql state=started enabled=yes
