- name: update libpam-ldap configuration
  shell: rm /etc/pam_ldap.conf || true; dpkg-reconfigure libpam-ldap -f noninteractive
  notify: pam-auth-update

- name: pam-auth-update
  shell: DEBIAN_FRONTEND=noninteractive pam-auth-update

- name: update libnss-ldap configuration
  shell: rm /etc/libnss_ldap.conf || true; dpkg-reconfigure libnss-ldap -f noninteractive
  notify: restart nscd

- include: service.yaml
  vars:
    service_name: nscd
